# Generated by Codex on 2026-04-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0037_project_quality_fields'),
        ('tasks', '0061_task_project_file_upload_idx_async'),
        ('users', '0012_user_identity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                (
                    'annotation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='collaboration_comments',
                        to='tasks.annotation',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='collaboration_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collaboration_comments',
                        to='projects.project',
                    ),
                ),
                (
                    'resolved_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='resolved_collaboration_comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collaboration_comments',
                        to='tasks.task',
                    ),
                ),
            ],
            options={
                'db_table': 'collaboration_comment',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
