# Generated by Django 5.1.15 on 2026-04-01 09:22

import django.db.models.deletion
from django.db import migrations, models


def assign_default_workspace_to_existing_projects(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Workspace = apps.get_model('organizations', 'Workspace')
    Project = apps.get_model('projects', 'Project')

    for organization in Organization.objects.all().iterator():
        workspace, _ = Workspace.objects.get_or_create(
            organization_id=organization.id,
            is_default=True,
            defaults={
                'title': '默认工作区',
                'description': '系统自动创建的默认工作区',
                'created_by_id': organization.created_by_id,
            },
        )
        Project.objects.filter(organization_id=organization.id, workspace__isnull=True).update(workspace_id=workspace.id)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_workspace"),
        ("projects", "0034_project_annotator_evaluation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organizations.workspace",
            ),
        ),
        migrations.RunPython(assign_default_workspace_to_existing_projects, migrations.RunPython.noop),
    ]
