# Generated by Django 5.1.15 on 2026-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                    ("manager", "Manager"),
                ],
                default="annotator",
                help_text="Project member role",
                max_length=32,
            ),
        ),
    ]
