# Generated by Codex on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0036_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='low_trust_threshold',
            field=models.FloatField(
                default=0.0,
                help_text='Annotator trust score threshold (0.0-1.0) for quality guardrails',
                verbose_name='low trust threshold',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_rules',
            field=models.JSONField(
                default=dict,
                help_text='Quality guardrails and agreement strategies for enterprise workflows',
                null=True,
                verbose_name='quality rules',
            ),
        ),
    ]
