# Generated by Codex on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_user_custom_hotkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_external_id',
            field=models.CharField(
                blank=True,
                help_text='External identity ID from SAML/SCIM/LDAP provider',
                max_length=255,
                null=True,
                unique=True,
                verbose_name='identity external id',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_provider',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Current source provider for identity synchronization',
                max_length=32,
                verbose_name='identity provider',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_synced_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Latest synchronization timestamp from identity provider',
                null=True,
                verbose_name='identity synced at',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_managed',
            field=models.BooleanField(
                default=False,
                help_text='Whether this user account is managed by external identity provider',
                verbose_name='is identity managed',
            ),
        ),
    ]
