# Generated by Codex on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0007_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='external_group_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='SCIM group identifier for workspace synchronization',
                max_length=255,
                verbose_name='external group id',
            ),
        ),
    ]
