const DEFAULT_HOTKEYS_RAW = [
  // Annotation Controls
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "Submit Annotation",
    key: "ctrl+enter",
    description: "Submit the current annotation",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "Skip Task",
    key: "ctrl+space",
    description: "Skip the current task",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "Undo",
    key: "ctrl+z",
    description: "Undo last action",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "Redo",
    key: "ctrl+shift+z",
    description: "Redo previously undone action",
    active: true,
  },

  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "Focus Previous Task",
    key: "shift+up",
    description: "Move focus to the previous task",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "Focus Next Task",
    key: "shift+down",
    description: "Move focus to the next task",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "Focus Closed Task",
    key: "shift+left",
    description: "Focus on the closed task column",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "Focus Open Task",
    key: "shift+right",
    description: "Focus on the open task column",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "Toggle Bulk Sidebar",
    key: "shift+.",
    description: "Minimize or expand bulk actions sidebar",
    active: true,
  },

  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "Delete All Regions",
    key: "ctrl+backspace",
    description: "Remove all regions",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "Focus First Region",
    key: "enter",
    description: "Move focus to the first focusable region",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "Create Region Relation",
    key: "alt+r",
    description: "Create a relation between selected regions",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "Toggle Region Visibility",
    key: "alt+h",
    description: "Show or hide the selected region",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "Toggle All Region Visibility",
    key: "ctrl+h",
    description: "Show or hide all regions",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "Lock Region",
    key: "alt+l",
    description: "Lock or unlock the selected region",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "Edit Region Metadata",
    key: "alt+m",
    description: "Edit metadata for selected region",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "Unselect Region",
    key: "u",
    description: "Deselect the currently selected region",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "Exit Region Mode",
    key: "escape",
    description: "Exit relation mode and unselect region",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "Delete Selected Region",
    key: "backspace",
    description: "Delete currently selected region",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "Cycle Regions",
    key: "alt+.",
    description: "Cycle through all regions",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "Duplicate Region",
    key: "ctrl+d",
    description: "Create a copy of the selected region",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "Delete Segment",
    key: "delete",
    description: "Delete selected segment",
    active: true,
  },

  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "Rewind 1 Second",
    key: "ctrl+b",
    description: "Rewind the audio by 1 second",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "Play / Pause Audio",
    key: "ctrl+p",
    description: "Toggle audio playback",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "Step Back",
    key: "alt+a",
    description: "Step back one frame",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "Step Forward",
    key: "alt+d",
    description: "Step forward one frame",
    active: true,
  },

  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "Play / Pause Video",
    key: "ctrl+alt+space",
    description: "Toggle video playback",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "Step Back",
    key: "alt+left",
    description: "Step one frame backward",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "Step Forward",
    key: "alt+right",
    description: "Step one frame forward",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "Previous Keyframe",
    key: "ctrl+alt+left",
    description: "Jump to previous keyframe",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "Next Keyframe",
    key: "ctrl+alt+right",
    description: "Jump to next keyframe",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "Seek Backward",
    key: "alt+left",
    description: "Seek video backward",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "First Frame",
    key: "shift+ctrl+alt+left",
    description: "Jump to first frame",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "Seek Forward",
    key: "shift+alt+right",
    description: "Seek video forward",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "Last Frame",
    key: "shift+ctrl+alt+right",
    description: "Jump to last frame",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "Hop Backward",
    key: "shift+alt+left",
    description: "Hop backward quickly",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "Hop Forward",
    key: "shift+alt+right",
    description: "Hop forward quickly",
    active: true,
  },

  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "Extend Left",
    key: "left",
    description: "Extend the region to the left",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "Extend Right",
    key: "right",
    description: "Extend the region to the right",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "Shrink Left",
    key: "alt+left",
    description: "Shrink the region from the left",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "Shrink Right",
    key: "alt+right",
    description: "Shrink the region from the right",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "Extend Left (Large)",
    key: "shift+left",
    description: "Extend region left significantly",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "Extend Right (Large)",
    key: "shift+right",
    description: "Extend region right significantly",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "Shrink Left (Large)",
    key: "shift+alt+left",
    description: "Shrink region from left significantly",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "Shrink Right (Large)",
    key: "shift+alt+right",
    description: "Shrink region from right significantly",
    active: true,
  },

  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "Previous Image",
    key: "ctrl+left",
    description: "View previous image",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "Next Image",
    key: "ctrl+right",
    description: "View next image",
    active: true,
  },

  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "Zoom In",
    key: "ctrl+plus",
    description: "Zoom in on the image",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "Pan Image",
    key: "H",
    description: "Pan around the image",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "Zoom to Fit",
    key: "shift+1",
    description: "Zoom to fit the full image in view",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "Zoom to 100%",
    key: "shift+2",
    description: "Zoom to actual image size (100%)",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "Zoom Out",
    key: "ctrl+minus",
    description: "Zoom out of the image",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "Move Tool",
    key: "V",
    description: "Select the move tool to reposition annotations",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "Brush Tool",
    key: "B",
    description: "Select the brush tool",
    active: true,
  },

  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "Ellipse Tool",
    key: "O",
    description: "Select the ellipse tool",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "Eraser Tool",
    key: "E",
    description: "Select the eraser tool",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "Auto Detect",
    key: "M",
    description: "Use the auto-detect tool to automatically suggest regions",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "Key Point Tool",
    key: "K",
    description: "Select the key point annotation tool",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "Magic Wand",
    key: "W",
    description: "Select the magic wand tool for smart region selection",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "Polygon Tool",
    key: "P",
    description: "Select the polygon annotation tool",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "Rectangle Tool",
    key: "R",
    description: "Select the rectangle annotation tool",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "3-Point Rectangle",
    key: "shift+R",
    description: "Draw a rotated rectangle using 3-point selection",
    active: true,
  },

  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "Rotate Left",
    key: "alt+left",
    description: "Rotate the image 90° to the left",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "Rotate Right",
    key: "alt+right",
    description: "Rotate the image 90° to the right",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "Decrease Tool Size",
    key: "[",
    description: "Decrease tool size",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "Increase Tool Size",
    key: "]",
    description: "Increase tool size",
    active: true,
  },

  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "Next Phrase",
    key: "ctrl+down",
    description: "Navigate to the next phrase in paragraph view",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "Previous Phrase",
    key: "ctrl+up",
    description: "Navigate to the previous phrase in paragraph view",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "Select All and Annotate",
    key: "ctrl+shift+a",
    description: "Select all text in current phrase and create annotation",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "Next Region in Phrase",
    key: "ctrl+right",
    description: "Navigate to the next region within current phrase",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "Previous Region in Phrase",
    key: "ctrl+left",
    description: "Navigate to the previous region within current phrase",
    active: true,
  },
];

const HOTKEY_TEXT_ZH = {
  "Submit Annotation": "提交标注",
  "Submit the current annotation": "提交当前标注",
  "Skip Task": "跳过任务",
  "Skip the current task": "跳过当前任务",
  Undo: "撤销",
  "Undo last action": "撤销上一步操作",
  Redo: "重做",
  "Redo previously undone action": "重做上一步撤销的操作",
  "Focus Previous Task": "聚焦上一条任务",
  "Move focus to the previous task": "将焦点移动到上一条任务",
  "Focus Next Task": "聚焦下一条任务",
  "Move focus to the next task": "将焦点移动到下一条任务",
  "Focus Closed Task": "聚焦已关闭任务",
  "Focus on the closed task column": "聚焦到已关闭任务列",
  "Focus Open Task": "聚焦未关闭任务",
  "Focus on the open task column": "聚焦到未关闭任务列",
  "Toggle Bulk Sidebar": "切换批量操作侧边栏",
  "Minimize or expand bulk actions sidebar": "折叠或展开批量操作侧边栏",
  "Delete All Regions": "删除所有区域",
  "Remove all regions": "移除所有区域",
  "Focus First Region": "聚焦第一个区域",
  "Move focus to the first focusable region": "将焦点移动到第一个可聚焦区域",
  "Create Region Relation": "创建区域关系",
  "Create a relation between selected regions": "在所选区域之间创建关系",
  "Toggle Region Visibility": "切换区域可见性",
  "Show or hide the selected region": "显示或隐藏选中区域",
  "Toggle All Region Visibility": "切换全部区域可见性",
  "Show or hide all regions": "显示或隐藏所有区域",
  "Lock Region": "锁定区域",
  "Lock or unlock the selected region": "锁定或解锁选中区域",
  "Edit Region Metadata": "编辑区域元数据",
  "Edit metadata for selected region": "编辑选中区域的元数据",
  "Unselect Region": "取消选择区域",
  "Deselect the currently selected region": "取消当前选中区域",
  "Exit Region Mode": "退出区域模式",
  "Exit relation mode and unselect region": "退出关系模式并取消区域选择",
  "Delete Selected Region": "删除选中区域",
  "Delete currently selected region": "删除当前选中区域",
  "Cycle Regions": "循环切换区域",
  "Cycle through all regions": "在所有区域间循环切换",
  "Duplicate Region": "复制区域",
  "Create a copy of the selected region": "复制选中区域",
  "Delete Segment": "删除片段",
  "Delete selected segment": "删除选中片段",
  "Rewind 1 Second": "回退1秒",
  "Rewind the audio by 1 second": "音频回退1秒",
  "Play / Pause Audio": "播放/暂停音频",
  "Toggle audio playback": "切换音频播放状态",
  "Step Back": "后退一帧",
  "Step back one frame": "后退一帧",
  "Step Forward": "前进一帧",
  "Step forward one frame": "前进一帧",
  "Play / Pause Video": "播放/暂停视频",
  "Toggle video playback": "切换视频播放状态",
  "Step one frame backward": "后退一帧",
  "Step one frame forward": "前进一帧",
  "Previous Keyframe": "上一个关键帧",
  "Jump to previous keyframe": "跳转到上一个关键帧",
  "Next Keyframe": "下一个关键帧",
  "Jump to next keyframe": "跳转到下一个关键帧",
  "Seek Backward": "向后跳转",
  "Seek video backward": "视频向后跳转",
  "First Frame": "第一帧",
  "Jump to first frame": "跳转到第一帧",
  "Seek Forward": "向前跳转",
  "Seek video forward": "视频向前跳转",
  "Last Frame": "最后一帧",
  "Jump to last frame": "跳转到最后一帧",
  "Hop Backward": "快速后跳",
  "Hop backward quickly": "快速向后跳转",
  "Hop Forward": "快速前跳",
  "Hop forward quickly": "快速向前跳转",
  "Extend Left": "向左扩展",
  "Extend the region to the left": "向左扩展区域",
  "Extend Right": "向右扩展",
  "Extend the region to the right": "向右扩展区域",
  "Shrink Left": "左侧收缩",
  "Shrink the region from the left": "从左侧收缩区域",
  "Shrink Right": "右侧收缩",
  "Shrink the region from the right": "从右侧收缩区域",
  "Extend Left (Large)": "大幅向左扩展",
  "Extend region left significantly": "大幅向左扩展区域",
  "Extend Right (Large)": "大幅向右扩展",
  "Extend region right significantly": "大幅向右扩展区域",
  "Shrink Left (Large)": "大幅左侧收缩",
  "Shrink region from left significantly": "大幅从左侧收缩区域",
  "Shrink Right (Large)": "大幅右侧收缩",
  "Shrink region from right significantly": "大幅从右侧收缩区域",
  "Previous Image": "上一张图片",
  "View previous image": "查看上一张图片",
  "Next Image": "下一张图片",
  "View next image": "查看下一张图片",
  "Zoom In": "放大",
  "Zoom in on the image": "放大图像",
  "Pan Image": "平移图像",
  "Pan around the image": "在图像中平移",
  "Zoom to Fit": "适应窗口",
  "Zoom to fit the full image in view": "缩放以完整显示图像",
  "Zoom to 100%": "缩放至100%",
  "Zoom to actual image size (100%)": "缩放到图像实际大小（100%）",
  "Zoom Out": "缩小",
  "Zoom out of the image": "缩小图像",
  "Move Tool": "移动工具",
  "Select the move tool to reposition annotations": "选择移动工具以调整标注位置",
  "Brush Tool": "画笔工具",
  "Select the brush tool": "选择画笔工具",
  "Ellipse Tool": "椭圆工具",
  "Select the ellipse tool": "选择椭圆工具",
  "Eraser Tool": "橡皮擦工具",
  "Select the eraser tool": "选择橡皮擦工具",
  "Auto Detect": "自动检测",
  "Use the auto-detect tool to automatically suggest regions": "使用自动检测工具自动建议区域",
  "Key Point Tool": "关键点工具",
  "Select the key point annotation tool": "选择关键点标注工具",
  "Magic Wand": "魔棒工具",
  "Select the magic wand tool for smart region selection": "选择魔棒工具进行智能区域选择",
  "Polygon Tool": "多边形工具",
  "Select the polygon annotation tool": "选择多边形标注工具",
  "Rectangle Tool": "矩形工具",
  "Select the rectangle annotation tool": "选择矩形标注工具",
  "3-Point Rectangle": "三点矩形",
  "Draw a rotated rectangle using 3-point selection": "使用三点方式绘制旋转矩形",
  "Rotate Left": "向左旋转",
  "Rotate the image 90° to the left": "将图像向左旋转90°",
  "Rotate Right": "向右旋转",
  "Rotate the image 90° to the right": "将图像向右旋转90°",
  "Decrease Tool Size": "减小工具尺寸",
  "Decrease tool size": "减小工具尺寸",
  "Increase Tool Size": "增大工具尺寸",
  "Increase tool size": "增大工具尺寸",
  "Next Phrase": "下一短语",
  "Navigate to the next phrase in paragraph view": "在段落视图中跳转到下一短语",
  "Previous Phrase": "上一短语",
  "Navigate to the previous phrase in paragraph view": "在段落视图中跳转到上一短语",
  "Select All and Annotate": "全选并标注",
  "Select all text in current phrase and create annotation": "选中当前短语全部文本并创建标注",
  "Next Region in Phrase": "短语内下一区域",
  "Navigate to the next region within current phrase": "在当前短语内跳转到下一个区域",
  "Previous Region in Phrase": "短语内上一区域",
  "Navigate to the previous region within current phrase": "在当前短语内跳转到上一个区域",
};

const t = (text) => (text ? (HOTKEY_TEXT_ZH[text] ?? text) : text);

export const DEFAULT_HOTKEYS = DEFAULT_HOTKEYS_RAW.map((item) => ({
  ...item,
  label: t(item.label),
  description: t(item.description),
}));

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "标注操作",
    description: "用于提交、跳过、撤销和重做等常见标注操作的快捷键",
  },

  {
    id: "data_manager",
    title: "数据管理",
    description: "用于在项目数据管理器中浏览和管理任务的快捷键",
  },

  {
    id: "regions",
    title: "区域管理",
    description: "用于创建、选择和操作标注区域的快捷键",
  },

  {
    id: "tools",
    title: "工具",
    description: "用于图像标注时控制工具面板的快捷键",
  },

  {
    id: "audio",
    title: "音频控制",
    description: "用于音频播放与导航的快捷键",
  },
  {
    id: "video",
    title: "视频控制",
    description: "用于视频播放与导航的快捷键",
  },
  {
    id: "timeseries",
    title: "时序控制",
    description: "用于操作时序数据区域的快捷键",
  },
  {
    id: "image_gallery",
    title: "图像集导航",
    description: "用于多图任务中切换图片的快捷键",
  },
  {
    id: "paragraphs",
    title: "段落导航",
    description: "用于在段落/对话视图中切换短语与区域的快捷键",
  },
];

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
